export enum ActionTypes {
SET_ERROR = 'SET_ERROR',
SET_LOADING = 'SET_LOADING',
SET_PHONES = 'SET_PHONES',
SET_FILTER_QUERY = 'SET_FILTER_QUERY',
SET_SORT = 'SET_SORT',
ADD_ITEM_IN_BASKET = 'ADD_ITEM_IN_BASKET',
DELETE_ITEM_FROM_BASKET = 'DELETE_ITEM_FROM_BASKET',
CHANGE_QUANTITY_ITEM = 'CHANGE_QUANTITY_ITEM',
DELETE_ITEM_FROM_FEATURED = 'DELETE_ITEM_FROM_FEATURED',
ADD_ITEM_IN_FEATURED = 'ADD_ITEM_IN_FEATURED',
}
